### ISSUE TITLE
MiHome relays

### ISSUE THREAD

**Issue by thd99** [jamesrodda/homebridge-mihomegateway#1]
MiHome relays are the same as MiHome switches, so adding:

```
  switch (device.device_type) {
    case "light":
      serviceType = Service.Switch;
      break;
    case "relay":
      serviceType = Service.Switch;
      break;
default:
```

works great :)

**Comment by jamesrodda** [comment]
Nice one! Feel free to submit a PR or I'll incorporate that next time I make any updates. Thanks.

**Comment by jamesrodda** [comment]
Finally got round to doing this :) New release incoming... #2
