### ISSUE TITLE
Error 503 in event log for all Mihome devices

### ISSUE THREAD

**Issue by Gordon-Newell** [jamesrodda/homebridge-mihomegateway#22]
[05/08/2021, 20:48:27] [MiHomeGateway] Error getting subdevice information: Living Room Lamp Unexpected statusCode from getSubDeviceInfo: 503

**Comment by Gordon-Newell** [comment]
More information.

Homebdrige version : v1.3.4
Node : v14.17.4
NPM : v7.20.4

**Comment by jamesrodda** [comment]
Hi, a 503 status code indicates the service was unavailable... Are you still seeing this issue? I can manually call the API externally to the plugin and also use the plugin itself.

**Comment by Gordon-Newell** [comment]
It was working, but was reporting the error, seems to have resolved itself now, so assuming it was an issue at MiHome's end
