### ISSUE TITLE
Adding a collabrator

### ISSUE THREAD

**Issue by chriscn** [jamesrodda/homebridge-mihomegateway#5]
Hi James,
I am a big fan of this project, however I would like to make some changes, including a potential rewrite over the summer. I personally use this on my own homebridge setup but everytime I undergo a reinstallation I have to make some changes including some more recent commits. 

My proposition is to make me a write collabrator on the GitHub and NPM so that I can independently push some new changes. 

Best Wishes,
Christopher Nethercott

**Comment by jamesrodda** [comment]
Hi Christopher,

Sorry about the delay in getting back to you.

I'm not sure I'm up for handing over a chunk of control of this project if I'm totally honest. Although it doesn't see many changes, I quite like having this "in my name".

What "recent commits" do you have to make changes for? More than happy to have review any PRs you have.

Hope that's ok.

Cheers,
James

**Comment by chriscn** [comment]
Hi James,
It was more for the fact that although the GitHub had been updated the NPM package had not. Not to worry as I have decided to just work on my [own](https://github.com/chriscn/homebridge-mihome4u). All the best

Christopher
